
export const CalculatorActionTypes = {
  FETCH_EXCHANGE_RATE_START: 'FETCH_EXCHANGE_RATE_START',
  FETCH_EXCHANGE_RATE_SUCCESS: 'FETCH_EXCHANGE_RATE_SUCCESS',
  FETCH_EXCHANGE_RATE_FAILURE: 'FETCH_EXCHANGE_RATE_FAILURE',
  FETCH_ACC_BASECHARGE_START: 'FETCH_ACC_BASECHARGE_START',
  FETCH_ACC_BASECHARGE_SUCCESS: 'FETCH_ACC_BASECHARGE_SUCCESS',
  FETCH_ACC_BASECHARGE_FAILURE: 'FETCH_ACC_BASECHARGE_FAILURE'
};

export default CalculatorActionTypes;